adminapp/urls.py
from django.urls import path
from adminapp.views import (
    users,
    user_create,
    user_update,
    product_update,
    user_delete,
    category_create,
    categories,
    category_delete,
    category_update,
    products,
    product_read,
    product_create,
    product_delete,
)

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', user_create, name='user_create'),
    path('users/read/', users, name='users'),
    path('users/update/<int:pk>/', user_update, name='user_update'),
    path('users/delete/<int:pk>/', user_delete, name='user_delete'),

    path('categories/create/', category_create, name='category_create'),
    path('categories/read/', categories, name='categories'),
    path('categories/update/<int:pk>/', category_update, name='category_update'),
    path('categories/delete/<int:pk>/', category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/', product_create, name='product_create'),
    path('products/read/category/<int:pk>/', products, name='products'),
    path('products/read/<int:pk>/', product_read, name='product_read'),
    path('products/update/<int:pk>/', product_update, name='product_update'),
    path('products/delete/<int:pk>/', product_delete, name='product_delete'),
]

authapp/urls.py
from django.urls import path

from .views import login, logout, register, edit, verify

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify'),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from geekshop.views import index, contact

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('mainapp.urls', namespace='products'), name='products'),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff'), name='admin_staff'),
    path('auth/', include('authapp.urls', namespace='auth'), name='auth'),
    path('basket/', include('basketapp.urls', namespace='basket'), name='basket'),
    path('', index, name='index'),
    path('contact/', contact, name='contact'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py

from django.urls import path
from .views import products, product

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
    path('category/<int:pk>/page/<int:page>/', products, name='page'),
    path('product/<int:pk>/', product, name='product'),
]

adminapp/models.py
from django import forms

adminapp/forms.py
from django import forms

from mainapp.models import ProductCategory


class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from adminapp.forms import ProductCategoryEditForm
from authapp.forms import ShopUserRegisterForm, ShopUserEditForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product
from django.contrib.auth.decorators import user_passes_test


def users(request):
    title = 'админка/пользователи'

    users_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')

    context = {
        'title': title,
        'objects': users_list
    }

    return render(request, 'adminapp/users.html', context)


def user_create(request):
    title = 'пользователи/создание'

    if request.method == 'POST':
        user_form = ShopUserRegisterForm(request.POST, request.FILES)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('admin_staff:users'))

    else:
        user_form = ShopUserRegisterForm()

    context = {
        'title': title,
        'update_form': user_form
    }

    return render(request, 'adminapp/user_update.html', context)


def user_update(request, pk):
    title = "пользователи/обновление"
    user = get_object_or_404(ShopUser, pk=pk)

    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=user)
        if edit_form.is_valid:
            edit_form.save()
            return HttpResponseRedirect(reverse("admin_staff:users"))
    else:
        edit_form = ShopUserEditForm(instance=user)

    context = {
        "title": title,
        "update_form": edit_form
    }

    return render(request, "adminapp/user_update.html", context)


def user_delete(request, pk):
    title = "удаление"

    user = get_object_or_404(ShopUser, pk=pk)

    context = {
        'title': title,
        'user_delete': user
    }

    if request.method == "POST":
        user.is_active = False
        user.save()
        return HttpResponseRedirect(reverse("admin_staff:users"))
        
    return render(request, "adminapp/user_update.html", context)


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    title = 'админка/категории'

    categories_list = ProductCategory.objects.all()

    context = {
        'title': title,
        'objects': categories_list
    }

    return render(request, 'adminapp/categories.html', context)


def category_create(request):
    title = "админка/создание категории"

    categories_list = ProductCategory.objects.all()
    new_category = ProductCategoryEditForm(request.POST, request.FILES)
    
    context = {
        "title": title,
        "categories_list": categories_list,
        "new_category": new_category,
    }

    if request.method == 'POST':
        if new_category.is_valid:
            new_category.save()
            return HttpResponseRedirect(reverse("admin_staff:categories"))
        else:
            return HttpResponseRedirect(reverse(("admin_staff:create")))
    
    return render(request, "adminapp/create.html", context)


def category_update(request, pk):
    title = "категории обновление"

    category = get_object_or_404(ProductCategory, pk=pk)
    category_form = ProductCategoryEditForm(request.POST, request.FILES, instance=category)

    context = {
        "title": title,
        "category": category,
        "category_form": category_form,
    }

    if request.method == "POST":
        if category_form.is_valid:
            category.save()
            return HttpResponseRedirect(reverse("admin_staff.categories"))
        else:
            return HttpResponseRedirect(reverse(("admin_staff:create")))

    return render(request, 'adminapp/create.html', context)


def category_delete(request, pk):
    title = "удаление"

    category = get_object_or_404(ProductCategory, pk=pk)
    categories_list = ProductCategory.objects.all()

    context ={
        "title": title,
        "category": category,
        'objects': categories_list
    }

    if request.method == "POST":
        if category.is_active is True:
            category.is_active = False
            category.save()
            return HttpResponseRedirect(reverse("admin_staff.categories"))
        else:
            return HttpResponseRedirect(reverse("admin_staff.categories"))

    return render(request, 'adminapp/categories.html', context)


def products(request, pk):
    pass


def product_create(request, pk):
    pass


def product_read(request, pk):
    pass


def product_update(request, pk):
    pass


def product_delete(request, pk):
    pass

adminapp/templates/adminapp/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'geekshop/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'adminapp/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'geekshop/fonts/font-awesome/css/font-awesome.css' %}">
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>

    {% block css %}
    {% endblock %}

    <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js'></script>
    <script src='{% static "adminapp/js/admin_script.js" %}'></script>
    {% block js %}
    {% endblock %}
</head>
<body id="body-pd">
    <header class="header" id="header">
        <div class="header_toggle"> <i class='bx bx-menu' id="header-toggle"></i> </div>
        <div class="header_img"> <img src="/media/{{ user.avatar }}" alt=""> </div>
    </header>
    <div class="l-navbar" id="nav-bar">
        <nav class="nav">
            <div> <a href="{% url 'index' %}" class="nav_logo">
                <i class='bx bx-layer nav_logo-icon'></i>
                <span class="nav_logo-name">Admin`ka</span>
            </a>
                <div class="nav_list">
                    {% include 'adminapp/includes/inc_menu.html' %}
                </div>
            </div>
            <a href="{% url 'auth:logout' %}" class="nav_link">
                <i class='bx bx-log-out nav_icon'></i>
                <span class="nav_name">Выход</span>
            </a>
        </nav>
    </div>
    <!--Container Main start-->
    <div class="height-100 bg-light">
        {% block content %}
        {% endblock %}
    </div>
    <!--Container Main end-->
</body>
</html>

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Категории</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fa fa-table mr-1"></i>
                    Список
                </div>
                <div class="card-body">
                   <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Категория</th>
                            <th>Описание</th>
                            <th></th>
                            <th></th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Категория</th>
                            <th>Описание</th>
                            <th></th>
                            <th></th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for category in objects %}
                            <tr>
                                <td>{{ category.name|title }}</td>
                                <td>{{ category.description|title }}</td>
                                <td class="text-center">
                                    <button>
                                        <a href='{% url "admin_staff:products" category.pk %}'> товары категории
                                        </a>
                                    </button>
                                </td>
                                <td class="text-center">
                                    <button>
                                        <a href="{% url 'admin_staff:category_update' category.pk %}">
 редактировать
                                        </a>
                                    </button>
                                </td>
                                <td class="text-center">
                                    <button>
                                        <a href="{% url 'admin_staff:category_delete' category.pk %}">
 удалить
                                        </a>
                                    </button>
                                </td>
                            </tr>
 {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>


                <div class="card-footer">
                    <a href="{% url 'adminapp:category_create' %}">
                        <button class="btn btn-success">Создать категорию</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

adminapp/templates/adminapp/create.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Пользователи</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Создание
            </div>
            <div class="card-body">
                <form class="form-horizontal" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <input class="form-control" type="submit" value="сохранить">
                </form>
                <form class="form-horizontal " method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input class="form-control" type="submit" value="удалить">
                </form>
            </div>

        </div>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Товары</h1>
            <div class="card" style="width: 18rem;">
                <img src="/media/{{ product.image }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.description }}</p>
                    <a href="{% url 'mainapp:product' product.pk %}" class="btn btn-primary">Go to web</a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Товары</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Редактирование/Создание
            </div>
            <div class="card-body">
                <form class="form-horizontal" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ update_form.as_p }}
                    <input class="form-control" type="submit" value="сохранить">
                </form>
            </div>

        </div>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Продукты</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                {{ category.name|title }}
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Изображение</th>
                            <th>Наименование</th>
                            <th>Краткое описание</th>
                            <th>Цена</th>
                            <th>Количество</th>
                            <th>Подробнее</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Изображение</th>
                            <th>Наименование</th>
                            <th>Краткое описание</th>
                            <th>Цена</th>
                            <th>Количество</th>
                            <th>Подробнее</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for product in objects %}
                            <tr>
                                <td><img src="/media/{{ product.image }}"></td>
                                <td>{{ product.name }}</td>
                                <td>{{ product.short_desc }}</td>
                                <td>{{ product.price }}</td>
                                <td>{{ product.quantity }}</td>
                                <td class="text-center">
                                    <button>
                                        <a href="{% url 'admin_staff:product_read' product.pk %}">
                                            Подробнее
                                        </a>
                                    </button>
                                </td>
                                <td class="text-center">
                                    <button>
                                        <a href="{% url 'admin_staff:product_update' product.pk %}">
                                            Радактировать
                                        </a>
                                    </button>
                                </td>
                                <td class="text-center">
                                    <button>
                                        <a href="{% url 'admin_staff:product_delete' product.pk %}">
                                            удалить
                                        </a>
                                    </button>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:product_create' category.pk %}">
                    <button class="btn btn-success">Создать товар</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Пользователи</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Создание
            </div>
            <div class="card-body">
                <form class="form-horizontal" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ update_form.as_p }}
                    <input class="form-control" type="submit" value="сохранить">
                </form>
                <form class="form-horizontal " method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input class="form-control" type="submit" value="удалить">
                </form>
            </div>

        </div>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid">
        <h1 class="mt-4">Пользователи</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Пользователи
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for user in objects %}
                            <tr>
                                <td><a href="{% url 'adminapp:user_update' user.id %}" style="color: 000">{{ user.username }}</a></td>
                                <td>{{ user.first_name }}</td>
                                <td>{{ user.last_name }}</td>
                                <td>{{ user.email }}</td>
                                <td class="text-center">
                                    {% if user.is_staff %}
                                        <i class="fa fa-check-circle"></i>
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if user.is_active %}
                                        <i class="fa fa-check-circle"></i>
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:user_create' %}">
                    <button class="btn btn-success">Создать пользователя</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}