adminapp/urls.py
from django.urls import path
from adminapp.views import (
    users,
    user_create,
    user_update,
    product_update,
    user_delete,
    category_create,
    categories,
    category_delete,
    category_update,
    products,
    product_read,
    product_create,
    product_delete,
)

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', user_create, name='user_create'),
    path('users/read/', users, name='users'),
    path('users/update/<int:pk>/', user_update, name='user_update'),
    path('users/delete/<int:pk>/', user_delete, name='user_delete'),

    path('categories/create/', category_create, name='category_create'),
    path('categories/read/', categories, name='categories'),
    path('categories/update/<int:pk>/', category_update, name='category_update'),
    path('categories/delete/<int:pk>/', category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/', product_create, name='product_create'),
    path('products/read/category/<int:pk>/', products, name='products'),
    path('products/read/<int:pk>/', product_read, name='product_read'),
    path('products/update/<int:pk>/', product_update, name='product_update'),
    path('products/delete/<int:pk>/', product_delete, name='product_delete'),
]

authapp/urls.py
from django.urls import path

from .views import login, logout, register, edit, verify

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify'),
]

basketapp/urls.py
from django.urls import path
from .views import basket, basket_add, basket_remove, basket_edit

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>)/', basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit')
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from geekshop.views import index, contact

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('mainapp.urls', namespace='products'), name='products'),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff'), name='admin_staff'),
    path('auth/', include('authapp.urls', namespace='auth'), name='auth'),
    path('basket/', include('basketapp.urls', namespace='basket'), name='basket'),
    path('', index, name='index'),
    path('contact/', contact, name='contact'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py

from django.urls import path
from .views import products, product

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
    path('category/<int:pk>/page/<int:page>/', products, name='page'),
    path('product/<int:pk>/', product, name='product'),
]

ordersapp/urls.py
from django.urls import path

from ordersapp.views import OrderListView, OrderCreateView, OrderUpdateView, OrderDeleteView, OrderDetailView, \
    order_forming_complete, get_product_price, payment_result

app_name = 'ordersapp'
urlpatterns = [

    path('', OrderListView.as_view(), name='list'),
    path('create/', OrderCreateView.as_view(), name='create'),
    path('update/<int:pk>', OrderUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', OrderDeleteView.as_view(), name='delete'),
    path('read/<int:pk>', OrderDetailView.as_view(), name='read'),
    path('forming_complete/<int:pk>', order_forming_complete, name='forming_complete'),


    path('product/<int:pk>/price/', get_product_price, name='get_product_price'),
    path('payment/result/', payment_result, name='payment_result')
]

mainapp/models.py
from django.db import models

# Create your models here.


class ProductCategory(models.Model):
    href = models.TextField(blank=True, verbose_name="ссылка")
    name = models.CharField(verbose_name="имя", max_length=128, unique=True)
    description = models.TextField(verbose_name="описание", max_length=750, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории товаров'


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name="категория товара")
    name = models.CharField(verbose_name="имя", max_length=128, unique=True)
    short_description = models.CharField(verbose_name="короткое описание", max_length=256, blank=True)
    description = models.TextField(verbose_name="описание", max_length=1000, blank=True)
    img = models.ImageField(upload_to="products_img", blank=True, verbose_name="картинка")
    price = models.DecimalField(verbose_name="цена", max_digits=10, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='колличество', default=0)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'

mainapp/views.py
import random

from django.shortcuts import render, get_object_or_404

from basketapp.models import Basket
from mainapp.models import Product, ProductCategory


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    return same_products


def get_hot_product():
    products = Product.objects.all()
    return random.sample(list(products), 1)[0]


def products(request, pk=None):
    title = "каталог"
    links_menu = ProductCategory.objects.all()
    basket = get_basket(request.user)
    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    if pk is not None:
        if pk == 0:
            products = Product.objects.all().order_by('price')
            category = {'name': 'все'}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by('price')

        context = {
            "title": title,
            "link_menu": links_menu,
            "category": category,
            "related_products": products,
            "hot_product": hot_product,
            "basket": basket,
        }
        return render(request, 'mainapp/products.html', context)

    products = Product.objects.all().order_by('price')

    context = {
        "title": title,
        "link_menu": links_menu,
        "related_products": same_products,
        "products": products,
        "hot_product": hot_product,
        "basket": basket,
    }
    
    return render(request, 'mainapp/products.html', context)

mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>
    <meta name="csrf-token" content="{{ csrf_token }}">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

 {% block css %}

 {% endblock %}
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">GeekShop {% now "D d M Y" %} </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mainapp:products' %}">Каталог <i class="fas fa-shopping-bag"></i>
                    </a>
                </li>
 {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authapp:login' %}">Войти <i
                                class="fas fa-sign-in-alt"></i></a>
                    </li>
 {% else %}
                    <li class="nav-item">
{#                        <a class="nav-link" href="{% url 'authapp:edit' %}">{{ user.username }}#}
{# <i class="fas fa-user-circle"></i>#}
{# </a>#}

                        <div class="dropdown">
                            <a class="nav-link dropdown-toggle" href="" data-toggle="dropdown">
 {{ user.username|default:'Пользователь' }}
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="nav-link text-dark" href="{% url 'authapp:edit' %}">
 Профиль
                                    </a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" href="{% url 'orders:list' %}">
                                        Заказы
                                    </a>
                                </li>
                            </ul>
                        </div>


                    </li>
 {% if user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'adminapp:users' %}">
                                <i class="fas fa-users-cog"></i>
                            </a>
                        </li>
 {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authapp:logout' %}">Выйти <i class="fas fa-sign-out-alt"></i></a>
                    </li>
 {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %}

{% endblock %}

{% block footer %}

{% endblock %}
<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


<script src="{% static 'js/jquery.formset.js' %}"></script>
<script src="{% static 'js/order_scripts.js' %}"></script>


<!-- FontAwesome script -->
<script src="{% static  'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

mainapp/templates/mainapp/detail.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    <a href="{% url 'mainapp:products' %}" class="list-group-item">Все</a>
                </div>
            </div>

            <div class="col-lg-9">
                <div class="row my-5">
                    <div class="card" style="width: 20rem;">
                        <img src="/media/{{ product.image }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text">{{ product.description }}</p>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">{{ product.price }} руб</li>
                            <li class="list-group-item">В наличии: {{ product.quantity }}</li>
                        </ul>
                    </div>
                </div>

            </div>

        </div>
    </div>
{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2020</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static  'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">GeekShop Store</h1>
                    <p>
                        Новые образы и лучшие бренды на GeekShop Store.
                        Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'mainapp:products' %}">
                            Начать покупки
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'geekshop/base.html' %}
{% load static %}

{% block "content" %}

{% include 'geekshop/includes/inc_main_menu.html' %}
<div class="details">
    {% include 'mainapp/includes/inc_category_menu.html' %}


<div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="/media/{{ product.image }}">
            </div>
            <div class="slider-control">
                <div class="block">
                    <a href="#"><img src="/media/{{ product.image }}" style="width: 100%" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="/media/{{ product.image }}" style="width: 100%" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="/media/{{ product.image }}" style="width: 100%" alt="">
                        <div class="text"></div>
                    </a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">{{ product.name }}</h3>
            <h3 class="red">горячее предложение</h3>
            <p class="price"> {{ product.price }} <span>руб</span></p>
            <a href="{% url 'basket:add' product.pk %}" class="red-button">
                заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            <div class="description-text">
                {{ product.description }}
            </div>
        </div>
    </div>

    <div class="related">
        <div class="title clearfix">
            <h2>Похожие продукты</h2>
            <a class="explore" href="#">показать все <img src="/static/geekshop/img/arrow.png" alt=""></a>
        </div>
        <div class="related-products clearfix">
            {% for product_rel in related_products %}
            <div class="block">
                <a href="#"><img src="/media/{{ product_rel.image }}" alt="">
                    <div class="text">
                        <img src="/static/geekshop/img/icon-hover.png" alt="img">
                        <h4>{{ product_rel.name }}</h4>
                        <p>{{ product_rel.short_desc }} </p>
                        <p>{{ product_rel.category.name }} </p>
                    </div>
                </a>
            </div>

            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends "geekshop/base.html" %}
{% load static %}
{% block "title" %}Каталог{% endblock %}


{% block "content" %}
	<div class="details">
		{% include 'geekshop/includes/inc_main_menu.html' %}
		{% include 'mainapp/includes/inc_cat_menu.html' %}


		<div class="details-products">
			<div class="details-slider">
				<div class="slider-product">
					<img src="/media/{{ hot_product.img }}">
				</div>
				<div class="slider-control">
					<div class="block">
						<a href="#"><img src="/media/{{ hot_product.img }}" style="width: 100%" alt="">
							<div class="text"></div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="/media/{{ hot_product.img }}" style="width: 100%" alt="">
							<div class="text"></div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="/media/{{ hot_product.img }}" style="width: 100%" alt="">
							<div class="text"></div>
						</a>
					</div>
				</div>
			</div>

			<div class="description">
				<h3 class="big-bold">{{ hot_product.name }}</h3>
				<h3 class="red">горячее предложение</h3>
				<p class="price"> {{ hot_product.price }} <span>руб</span></p>
				<a href="#" class="red-button">
					заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
				</a>
				<div class="description-text">
					<p>{{ hot_product.description }}</p>
				</div>
			</div>
		</div>

    <div class="products_list" style="margin-top: 50px;">
    {% if category %}
      <div class="title clearfix">
        <h2>
          Категория: "{{ category.name|title }}"
        </h2>
      </div>
    {% endif %}
        <div class="related-products" style="display: flex; justify-content: center; margin-top: 20px;">
        {% for product in products %}
        <div class="block">
            <a href="{% url 'basket:add' product.pk %}"><img src="/media/{{ product.img }}" alt="">
                <div class="text">
                    <img src="/static/geekshop/img/icon-hover.png" alt="img">
                    <h4>{{ product.name }}</h4>
                    <p>{{ product.short_desc }} </p>
                    <p>{{ product.category.name }} </p>
                </div>
            </a>
        </div>
        {% endfor %}
    	</div>
    </div>

		<div class="related">
			<div class="title clearfix">
				<h2>Похожие продукты</h2>
				<a class="explore" href="#">показать все <img src="/static/geekshop/img/arrow.png" alt=""></a>
			</div>

			<div class="related-products clearfix">
				{% for product in related_products %}
				<div class="block">
					<a href="#"><img src="/media/{{ product.img }}" alt="">
						<div class="text">
							<img src="/static/geekshop/img/icon-hover.png" alt="img">
							<h4>{{ product.name }}</h4>
							<p>{{ product.short_description }} </p>
							<p>{{ product.category.name }} </p>
						</div>
					</a>
				</div>{% endfor %}
			</div>

		</div>


	<div class="clr"></div>
	</div>
{% endblock %}