adminapp/urls.py
from django.urls import path
from adminapp.views import (
    users,
    user_create,
    user_update,
    product_update,
    user_delete,
    category_create,
    categories,
    category_delete,
    category_update,
    products,
    product_read,
    product_create,
    product_delete,
)

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', user_create, name='user_create'),
    path('users/read/', users, name='users'),
    path('users/update/<int:pk>/', user_update, name='user_update'),
    path('users/delete/<int:pk>/', user_delete, name='user_delete'),

    path('categories/create/', category_create, name='category_create'),
    path('categories/read/', categories, name='categories'),
    path('categories/update/<int:pk>/', category_update, name='category_update'),
    path('categories/delete/<int:pk>/', category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/', product_create, name='product_create'),
    path('products/read/category/<int:pk>/', products, name='products'),
    path('products/read/<int:pk>/', product_read, name='product_read'),
    path('products/update/<int:pk>/', product_update, name='product_update'),
    path('products/delete/<int:pk>/', product_delete, name='product_delete'),
]

authapp/urls.py
from django.urls import path

from .views import login, logout, register, edit, verify

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify'),
]

basketapp/urls.py
from django.urls import path
from .views import basket, basket_add, basket_remove, basket_edit

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>)/', basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit')
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from geekshop.views import index, contact

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('mainapp.urls', namespace='products'), name='products'),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff'), name='admin_staff'),
    path('auth/', include('authapp.urls', namespace='auth'), name='auth'),
    path('basket/', include('basketapp.urls', namespace='basket'), name='basket'),
    path('', index, name='index'),
    path('contact/', contact, name='contact'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/views.py
from django.shortcuts import render


def index(request):
    context = {
        "slogan": "Лучшее предложение"
    }
    return render(request, 'geekshop/index.html', context)


def contact(request):
    context = {

    }
    return render(request, 'geekshop/contact.html', context)

geekshop/templates/geekshop/includes/inc_main_menu.html
<div class="header clearfix">
    <a href="{% url 'index' %}" class="logo"></a>
    <ul class="menu">
        <li><a href="{% url 'index' %}" class="active">домой</a></li>
        <li><a href="{% url 'products:index' %}">продукты</a></li>
        <li><a href="{% url 'contact' %}">контакты</a></li>
 {% if user.is_authenticated %}
        <li>
            <a href="{% url 'auth:edit' %}">
 {{ user.first_name|default:'Пользователь' }}
            </a>
        </li>
        {% if user.is_superuser %}
        <li>
            <a href="{% url 'admin_staff:users' %}">админка</a>
        </li>
        {% endif %}
        <li>
            <a href="{% url 'basket:view' %}" >
                <span>
                    {% if basket %}
                        {{ basket.0.total_cost|floatformat:0 }} руб
                        ({{ basket.0.total_quantity }} шт )
                    {% endif %}
                </span>
            </a>
        </li>
 {% endif %}
        <li>
 {% if user.is_authenticated %}
              <a href="{% url 'auth:logout' %}">выйти</a>
 {% else %}
              <a href="{% url 'auth:login' %}">войти</a>
 {% endif %}
        </li>
    </ul>
    <a href="#" class="search"></a>
</div>